import type { Food, Micros, Provenance } from './types';
import { ZERO_MICROS } from './types';

// `aliases` is required on every entry, so a food can't slip in findable only by its exact name.
function f(partial: Omit<Food, 'micros'> & { micros?: Partial<Micros> }): Food {
	return { ...partial, micros: { ...ZERO_MICROS, ...partial.micros } };
}

/**
 * Seed catalog. Each row carries a single provenance so the USDA and Open Food
 * Facts licenses never mix inside one entry.
 */
export const FOODS: Food[] = [
	f({
		id: 'egg-large',
		name: 'Egg, large',
		aliases: ['eggs', 'egg', 'scrambled eggs', 'boiled egg', 'fried egg'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '1 large',
		grams: 50,
		kcal: 72,
		protein: 6.3,
		carbs: 0.4,
		fat: 4.8,
		micros: {
			sodium: 71,
			potassium: 69,
			iron: 0.88,
			calcium: 28,
			vitaminD: 1.1,
			vitaminB12: 0.56,
			vitaminA: 80,
			folate: 24,
			zinc: 0.65,
			magnesium: 6,
			sugar: 0.2
		}
	}),
	f({
		id: 'egg-white',
		name: 'Egg white, large',
		aliases: ['egg whites', 'whites'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '1 large',
		grams: 33,
		kcal: 17,
		protein: 3.6,
		carbs: 0.2,
		fat: 0.1,
		micros: { sodium: 55, potassium: 54, vitaminB12: 0.03 }
	}),
	f({
		id: 'chicken-breast',
		name: 'Chicken breast, grilled',
		aliases: ['chicken', 'grilled chicken', 'chicken breast'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '100 g',
		grams: 100,
		kcal: 165,
		protein: 31,
		carbs: 0,
		fat: 3.6,
		micros: {
			sodium: 74,
			potassium: 256,
			iron: 0.4,
			zinc: 1,
			vitaminB12: 0.3,
			magnesium: 29,
			vitaminA: 6
		}
	}),
	f({
		id: 'chicken-thigh',
		name: 'Chicken thigh, roasted',
		aliases: ['thigh', 'chicken thighs'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '100 g',
		grams: 100,
		kcal: 209,
		protein: 26,
		carbs: 0,
		fat: 11,
		micros: { sodium: 84, potassium: 240, iron: 1.1, zinc: 2.4, vitaminB12: 0.4 }
	}),
	f({
		id: 'rotisserie-chicken',
		name: 'Rotisserie chicken, skinless',
		aliases: ['rotisserie', 'store chicken'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '100 g',
		grams: 100,
		kcal: 184,
		protein: 28,
		carbs: 0,
		fat: 8,
		micros: { sodium: 320, potassium: 250, iron: 0.9, vitaminB12: 0.3 }
	}),
	f({
		id: 'turkey-breast',
		name: 'Turkey breast, roasted',
		aliases: ['turkey', 'sliced turkey'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '100 g',
		grams: 100,
		kcal: 135,
		protein: 30,
		carbs: 0,
		fat: 1,
		micros: { sodium: 49, potassium: 300, iron: 0.6, zinc: 1.2, vitaminB12: 0.4 }
	}),
	f({
		id: 'ground-turkey',
		name: 'Ground turkey, 93%',
		aliases: ['turkey mince'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '100 g cooked',
		grams: 100,
		kcal: 176,
		protein: 27,
		carbs: 0,
		fat: 8,
		micros: { sodium: 80, potassium: 270, iron: 1.5, zinc: 3 }
	}),
	f({
		id: 'ground-beef',
		name: 'Ground beef, 93% lean',
		aliases: ['beef', 'hamburger meat', 'mince'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '100 g cooked',
		grams: 100,
		kcal: 182,
		protein: 25.6,
		carbs: 0,
		fat: 8,
		micros: { sodium: 72, potassium: 318, iron: 2.6, zinc: 6.3, vitaminB12: 2.5 }
	}),
	f({
		id: 'sirloin',
		name: 'Sirloin steak, grilled',
		aliases: ['steak', 'sirloin'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '100 g',
		grams: 100,
		kcal: 183,
		protein: 30,
		carbs: 0,
		fat: 6.5,
		micros: { sodium: 54, potassium: 350, iron: 2.4, zinc: 5.5, vitaminB12: 2.1 }
	}),
	f({
		id: 'salmon',
		name: 'Atlantic salmon, baked',
		aliases: ['salmon', 'fish'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '100 g',
		grams: 100,
		kcal: 206,
		protein: 22,
		carbs: 0,
		fat: 12,
		micros: {
			sodium: 59,
			potassium: 363,
			vitaminD: 11,
			vitaminB12: 3.2,
			vitaminA: 12
		}
	}),
	f({
		id: 'tuna-canned',
		name: 'Tuna, canned in water',
		aliases: ['tuna', 'canned tuna', 'tuna can'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '1 can drained (142 g)',
		grams: 142,
		kcal: 191,
		protein: 42,
		carbs: 0,
		fat: 1.4,
		micros: { sodium: 338, potassium: 333, vitaminD: 2.5, vitaminB12: 2.5 }
	}),
	f({
		id: 'shrimp',
		name: 'Shrimp, cooked',
		aliases: ['prawns', 'shrimp'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '100 g',
		grams: 100,
		kcal: 99,
		protein: 24,
		carbs: 0.2,
		fat: 0.3,
		micros: { sodium: 111, potassium: 259, iron: 0.5, vitaminB12: 1.1, zinc: 1.6 }
	}),
	f({
		id: 'cod',
		name: 'Cod, baked',
		aliases: ['white fish', 'cod'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '100 g',
		grams: 100,
		kcal: 82,
		protein: 18,
		carbs: 0,
		fat: 0.7,
		micros: { sodium: 78, potassium: 244, vitaminB12: 0.9, vitaminD: 0.8 }
	}),
	f({
		id: 'pork-tenderloin',
		name: 'Pork tenderloin, roasted',
		aliases: ['pork', 'pork loin'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '100 g',
		grams: 100,
		kcal: 143,
		protein: 26,
		carbs: 0,
		fat: 3.5,
		micros: { sodium: 47, potassium: 421, iron: 1, zinc: 2.4, vitaminB12: 0.6 }
	}),
	f({
		id: 'bacon',
		name: 'Bacon, pan-fried',
		aliases: ['bacon'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '1 slice',
		grams: 8,
		kcal: 43,
		protein: 3,
		carbs: 0.1,
		fat: 3.3,
		micros: { sodium: 185 }
	}),
	f({
		id: 'tofu-firm',
		name: 'Tofu, firm',
		aliases: ['tofu'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '100 g',
		grams: 100,
		kcal: 144,
		protein: 17,
		carbs: 3,
		fat: 9,
		micros: { calcium: 350, iron: 2.7, magnesium: 58, potassium: 237, sodium: 14 }
	}),
	f({
		id: 'tempeh',
		name: 'Tempeh',
		aliases: ['tempeh'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '100 g',
		grams: 100,
		kcal: 192,
		protein: 20,
		carbs: 8,
		fat: 11,
		micros: { iron: 2.7, calcium: 111, magnesium: 81, fiber: 5, potassium: 412 }
	}),
	f({
		id: 'lentils',
		name: 'Lentils, cooked',
		aliases: ['lentil', 'lentils'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '1 cup',
		grams: 198,
		kcal: 230,
		protein: 18,
		carbs: 40,
		fat: 0.8,
		micros: {
			fiber: 16,
			iron: 6.6,
			folate: 358,
			potassium: 731,
			magnesium: 71,
			sodium: 4
		}
	}),
	f({
		id: 'chickpeas',
		name: 'Chickpeas, cooked',
		aliases: ['garbanzo', 'chickpea', 'chickpeas'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '1 cup',
		grams: 164,
		kcal: 269,
		protein: 14.5,
		carbs: 45,
		fat: 4.2,
		micros: { fiber: 12.5, iron: 4.7, folate: 282, potassium: 477, sodium: 11 }
	}),
	f({
		id: 'black-beans',
		name: 'Black beans, cooked',
		aliases: ['black bean', 'beans'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '1 cup',
		grams: 172,
		kcal: 227,
		protein: 15,
		carbs: 41,
		fat: 0.9,
		micros: { fiber: 15, iron: 3.6, potassium: 611, folate: 256, magnesium: 120 }
	}),
	f({
		id: 'edamame',
		name: 'Edamame, shelled',
		aliases: ['edamame'],
		category: 'protein',
		provenance: 'usda',
		servingLabel: '1 cup',
		grams: 155,
		kcal: 188,
		protein: 18,
		carbs: 14,
		fat: 8,
		micros: { fiber: 8, iron: 3.5, folate: 482, potassium: 676, vitaminC: 9.5 }
	}),
	f({
		id: 'greek-yogurt',
		name: 'Greek yogurt, plain nonfat',
		aliases: ['yogurt', 'greek yogurt', 'nonfat yogurt'],
		category: 'dairy',
		provenance: 'usda',
		servingLabel: '170 g cup',
		grams: 170,
		kcal: 100,
		protein: 17,
		carbs: 6,
		fat: 0.7,
		micros: {
			calcium: 187,
			potassium: 240,
			sodium: 61,
			vitaminB12: 1.3,
			sugar: 6
		}
	}),
	f({
		id: 'greek-yogurt-whole',
		name: 'Greek yogurt, whole milk',
		aliases: ['full fat yogurt', 'whole milk yogurt'],
		category: 'dairy',
		provenance: 'usda',
		servingLabel: '170 g cup',
		grams: 170,
		kcal: 179,
		protein: 15,
		carbs: 6,
		fat: 9,
		micros: { calcium: 170, potassium: 220, vitaminB12: 1.1, sugar: 6 }
	}),
	f({
		id: 'cottage-cheese',
		name: 'Cottage cheese, 1%',
		aliases: ['cottage', 'cottage cheese'],
		category: 'dairy',
		provenance: 'usda',
		servingLabel: '1 cup',
		grams: 226,
		kcal: 163,
		protein: 28,
		carbs: 6,
		fat: 2.3,
		micros: { calcium: 138, sodium: 918, potassium: 220, vitaminB12: 1.4 }
	}),
	f({
		id: 'whey',
		name: 'Whey protein isolate',
		aliases: ['protein powder', 'whey', 'protein shake', 'scoop of protein'],
		category: 'protein',
		provenance: 'brand',
		servingLabel: '1 scoop (30 g)',
		grams: 30,
		kcal: 110,
		protein: 25,
		carbs: 2,
		fat: 0.5,
		micros: { sodium: 50, calcium: 120, potassium: 160 }
	}),
	f({
		id: 'core-power',
		name: 'Fairlife Core Power 26g',
		brand: 'Fairlife',
		aliases: ['core power', 'fairlife', 'protein shake'],
		barcode: '811620021015',
		category: 'protein',
		provenance: 'off',
		servingLabel: '1 bottle (414 ml)',
		grams: 414,
		kcal: 170,
		protein: 26,
		carbs: 8,
		fat: 4.5,
		micros: { calcium: 650, sodium: 260, potassium: 490, vitaminD: 5, sugar: 6 }
	}),
	f({
		id: 'peanut-butter',
		name: 'Peanut butter, smooth',
		aliases: ['pb', 'peanut butter'],
		category: 'fat',
		provenance: 'usda',
		servingLabel: '2 tbsp',
		grams: 32,
		kcal: 188,
		protein: 8,
		carbs: 6,
		fat: 16,
		micros: { fiber: 2, sodium: 136, magnesium: 57, potassium: 208, zinc: 0.9 }
	}),
	f({
		id: 'almonds',
		name: 'Almonds, raw',
		aliases: ['almond', 'almonds'],
		category: 'fat',
		provenance: 'usda',
		servingLabel: '1 oz (23 nuts)',
		grams: 28,
		kcal: 164,
		protein: 6,
		carbs: 6,
		fat: 14,
		micros: { fiber: 3.5, magnesium: 76, calcium: 76, potassium: 208 }
	}),
	f({
		id: 'walnuts',
		name: 'Walnuts',
		aliases: ['walnut', 'walnuts'],
		category: 'fat',
		provenance: 'usda',
		servingLabel: '1 oz',
		grams: 28,
		kcal: 185,
		protein: 4.3,
		carbs: 4,
		fat: 18.5,
		micros: { fiber: 1.9, magnesium: 45, potassium: 125 }
	}),
	f({
		id: 'chia',
		name: 'Chia seeds',
		aliases: ['chia'],
		category: 'fat',
		provenance: 'usda',
		servingLabel: '1 tbsp',
		grams: 12,
		kcal: 58,
		protein: 2,
		carbs: 5,
		fat: 3.7,
		micros: { fiber: 4.1, calcium: 75, magnesium: 40, potassium: 49 }
	}),
	f({
		id: 'oats',
		name: 'Oats, dry',
		aliases: ['oatmeal', 'oats', 'rolled oats', 'porridge'],
		category: 'grain',
		provenance: 'usda',
		servingLabel: '1/2 cup dry',
		grams: 40,
		kcal: 154,
		protein: 5.3,
		carbs: 27,
		fat: 2.6,
		micros: { fiber: 4, iron: 1.7, magnesium: 56, potassium: 140, zinc: 1.2 }
	}),
	f({
		id: 'brown-rice',
		name: 'Brown rice, cooked',
		aliases: ['rice', 'brown rice'],
		category: 'grain',
		provenance: 'usda',
		servingLabel: '1 cup',
		grams: 195,
		kcal: 216,
		protein: 5,
		carbs: 45,
		fat: 1.8,
		micros: { fiber: 3.5, magnesium: 84, potassium: 154 }
	}),
	f({
		id: 'white-rice',
		name: 'White rice, cooked',
		aliases: ['white rice', 'steamed rice'],
		category: 'grain',
		provenance: 'usda',
		servingLabel: '1 cup',
		grams: 158,
		kcal: 205,
		protein: 4.3,
		carbs: 45,
		fat: 0.4,
		micros: { fiber: 0.6, sodium: 2 }
	}),
	f({
		id: 'quinoa',
		name: 'Quinoa, cooked',
		aliases: ['quinoa'],
		category: 'grain',
		provenance: 'usda',
		servingLabel: '1 cup',
		grams: 185,
		kcal: 222,
		protein: 8,
		carbs: 39,
		fat: 3.6,
		micros: { fiber: 5.2, iron: 2.8, magnesium: 118, folate: 78, potassium: 318 }
	}),
	f({
		id: 'pasta',
		name: 'Pasta, cooked',
		aliases: ['spaghetti', 'noodles', 'pasta'],
		category: 'grain',
		provenance: 'usda',
		servingLabel: '1 cup',
		grams: 140,
		kcal: 220,
		protein: 8,
		carbs: 43,
		fat: 1.3,
		micros: { fiber: 2.5, folate: 126, iron: 1.8 }
	}),
	f({
		id: 'sourdough',
		name: 'Sourdough bread',
		aliases: ['toast', 'bread', 'sourdough', 'slice of toast'],
		category: 'grain',
		provenance: 'usda',
		servingLabel: '1 slice (40 g)',
		grams: 40,
		kcal: 105,
		protein: 4,
		carbs: 20,
		fat: 0.6,
		micros: { fiber: 1, sodium: 230, iron: 1.1, folate: 40 }
	}),
	f({
		id: 'wheat-bread',
		name: 'Whole wheat bread',
		aliases: ['wheat toast', 'whole wheat', 'wheat bread'],
		category: 'grain',
		provenance: 'usda',
		servingLabel: '1 slice',
		grams: 32,
		kcal: 81,
		protein: 4,
		carbs: 14,
		fat: 1.1,
		micros: { fiber: 1.9, sodium: 146, iron: 0.8, magnesium: 24 }
	}),
	f({
		id: 'daves-bread',
		name: '21 Whole Grains and Seeds',
		brand: "Dave's Killer Bread",
		aliases: ["dave's", 'dkb', 'killer bread'],
		barcode: '013764027954',
		category: 'grain',
		provenance: 'off',
		servingLabel: '1 slice',
		grams: 45,
		kcal: 110,
		protein: 5,
		carbs: 22,
		fat: 1.5,
		micros: { fiber: 5, sodium: 170, iron: 1.1, sugar: 5 }
	}),
	f({
		id: 'tortilla',
		name: 'Flour tortilla, 8 inch',
		aliases: ['wrap', 'tortilla'],
		category: 'grain',
		provenance: 'usda',
		servingLabel: '1 tortilla',
		grams: 49,
		kcal: 146,
		protein: 4,
		carbs: 25,
		fat: 3.7,
		micros: { fiber: 1.5, sodium: 331 }
	}),
	f({
		id: 'bagel',
		name: 'Bagel, plain',
		aliases: ['bagel'],
		category: 'grain',
		provenance: 'usda',
		servingLabel: '1 bagel (100 g)',
		grams: 100,
		kcal: 250,
		protein: 10,
		carbs: 49,
		fat: 1.5,
		micros: { fiber: 2.1, sodium: 430, iron: 3.6 }
	}),
	f({
		id: 'english-muffin',
		name: 'English muffin, whole wheat',
		aliases: ['english muffin'],
		category: 'grain',
		provenance: 'usda',
		servingLabel: '1 muffin',
		grams: 66,
		kcal: 134,
		protein: 6,
		carbs: 27,
		fat: 1.3,
		micros: { fiber: 4.4, sodium: 220, iron: 1.6 }
	}),
	f({
		id: 'potato',
		name: 'Potato, baked with skin',
		aliases: ['potato', 'baked potato'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '1 medium',
		grams: 173,
		kcal: 161,
		protein: 4.3,
		carbs: 37,
		fat: 0.2,
		micros: { fiber: 3.8, potassium: 926, vitaminC: 16.6, magnesium: 48 }
	}),
	f({
		id: 'sweet-potato',
		name: 'Sweet potato, baked',
		aliases: ['sweet potato', 'yam'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '1 medium',
		grams: 114,
		kcal: 103,
		protein: 2.3,
		carbs: 24,
		fat: 0.2,
		micros: {
			fiber: 3.8,
			vitaminA: 1096,
			potassium: 542,
			vitaminC: 22,
			magnesium: 31
		}
	}),
	f({
		id: 'banana',
		name: 'Banana',
		aliases: ['banana', 'bananas'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '1 medium',
		grams: 118,
		kcal: 105,
		protein: 1.3,
		carbs: 27,
		fat: 0.4,
		micros: { fiber: 3.1, potassium: 422, vitaminC: 10, magnesium: 32, sugar: 14 }
	}),
	f({
		id: 'apple',
		name: 'Apple',
		aliases: ['apple', 'apples'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '1 medium',
		grams: 182,
		kcal: 95,
		protein: 0.5,
		carbs: 25,
		fat: 0.3,
		micros: { fiber: 4.4, potassium: 195, vitaminC: 8.4, sugar: 19 }
	}),
	f({
		id: 'blueberries',
		name: 'Blueberries',
		aliases: ['blueberries', 'berries'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '1 cup',
		grams: 148,
		kcal: 84,
		protein: 1.1,
		carbs: 21,
		fat: 0.5,
		micros: { fiber: 3.6, vitaminC: 14, potassium: 114, sugar: 15 }
	}),
	f({
		id: 'strawberries',
		name: 'Strawberries',
		aliases: ['strawberry', 'strawberries'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '1 cup sliced',
		grams: 166,
		kcal: 53,
		protein: 1.1,
		carbs: 13,
		fat: 0.5,
		micros: { fiber: 3.3, vitaminC: 98, potassium: 254, folate: 40, sugar: 8 }
	}),
	f({
		id: 'avocado',
		name: 'Avocado',
		aliases: ['avocado', 'avo', 'half avocado'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '1/2 fruit',
		grams: 68,
		kcal: 114,
		protein: 1.3,
		carbs: 6,
		fat: 10.5,
		micros: { fiber: 5, potassium: 345, folate: 60, magnesium: 20, vitaminC: 6 }
	}),
	f({
		id: 'broccoli',
		name: 'Broccoli, steamed',
		aliases: ['broccoli'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '1 cup',
		grams: 156,
		kcal: 55,
		protein: 3.7,
		carbs: 11,
		fat: 0.6,
		micros: {
			fiber: 5.1,
			vitaminC: 101,
			vitaminA: 120,
			potassium: 457,
			folate: 168,
			calcium: 62
		}
	}),
	f({
		id: 'spinach',
		name: 'Spinach, raw',
		aliases: ['spinach'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '2 cups',
		grams: 60,
		kcal: 14,
		protein: 1.8,
		carbs: 2.2,
		fat: 0.2,
		micros: {
			fiber: 1.3,
			vitaminA: 281,
			vitaminC: 17,
			iron: 1.6,
			folate: 117,
			magnesium: 47,
			potassium: 334
		}
	}),
	f({
		id: 'mixed-greens',
		name: 'Mixed salad greens',
		aliases: ['salad', 'greens', 'lettuce', 'spring mix'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '2 cups',
		grams: 70,
		kcal: 14,
		protein: 1.2,
		carbs: 2.5,
		fat: 0.2,
		micros: { fiber: 1.2, vitaminA: 200, vitaminC: 12, folate: 50, potassium: 180 }
	}),
	f({
		id: 'kale',
		name: 'Kale, raw',
		aliases: ['kale'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '1 cup chopped',
		grams: 21,
		kcal: 7,
		protein: 0.6,
		carbs: 0.9,
		fat: 0.3,
		micros: { vitaminA: 98, vitaminC: 19, calcium: 53, potassium: 79 }
	}),
	f({
		id: 'tomato',
		name: 'Tomato',
		aliases: ['tomato', 'tomatoes'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '1 medium',
		grams: 123,
		kcal: 22,
		protein: 1.1,
		carbs: 4.8,
		fat: 0.2,
		micros: { vitaminC: 17, potassium: 292, folate: 18, fiber: 1.5 }
	}),
	f({
		id: 'cucumber',
		name: 'Cucumber',
		aliases: ['cucumber'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '1 cup sliced',
		grams: 104,
		kcal: 16,
		protein: 0.7,
		carbs: 3.6,
		fat: 0.1,
		micros: { potassium: 152, vitaminC: 3 }
	}),
	f({
		id: 'bell-pepper',
		name: 'Bell pepper, red',
		aliases: ['pepper', 'bell pepper', 'red pepper'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '1 medium',
		grams: 119,
		kcal: 31,
		protein: 1,
		carbs: 6,
		fat: 0.3,
		micros: { vitaminC: 152, vitaminA: 157, fiber: 2.1, potassium: 211 }
	}),
	f({
		id: 'carrot',
		name: 'Carrots',
		aliases: ['carrot', 'carrots'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '1 cup chopped',
		grams: 128,
		kcal: 52,
		protein: 1.2,
		carbs: 12,
		fat: 0.3,
		micros: { fiber: 3.6, vitaminA: 1069, potassium: 410, vitaminC: 7.6 }
	}),
	f({
		id: 'zucchini',
		name: 'Zucchini, cooked',
		aliases: ['zucchini', 'courgette'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '1 cup',
		grams: 180,
		kcal: 27,
		protein: 2,
		carbs: 5,
		fat: 0.4,
		micros: { potassium: 455, vitaminC: 13, fiber: 1.8 }
	}),
	f({
		id: 'asparagus',
		name: 'Asparagus, cooked',
		aliases: ['asparagus'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '1 cup',
		grams: 180,
		kcal: 40,
		protein: 4.3,
		carbs: 7.4,
		fat: 0.4,
		micros: { folate: 134, vitaminA: 90, fiber: 3.6 }
	}),
	f({
		id: 'mushrooms',
		name: 'Mushrooms, cooked',
		aliases: ['mushroom', 'mushrooms'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '1 cup',
		grams: 156,
		kcal: 44,
		protein: 3.4,
		carbs: 8,
		fat: 0.7,
		micros: { potassium: 555, vitaminD: 0.3, sodium: 2 }
	}),
	f({
		id: 'green-beans',
		name: 'Green beans, cooked',
		aliases: ['green beans'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '1 cup',
		grams: 125,
		kcal: 44,
		protein: 2.4,
		carbs: 10,
		fat: 0.3,
		micros: { fiber: 4, vitaminC: 12, vitaminA: 35, potassium: 146 }
	}),
	f({
		id: 'whole-milk',
		name: 'Whole milk',
		aliases: ['milk', 'whole milk'],
		category: 'dairy',
		provenance: 'usda',
		servingLabel: '1 cup',
		grams: 244,
		kcal: 149,
		protein: 8,
		carbs: 12,
		fat: 8,
		micros: {
			calcium: 276,
			vitaminD: 3.2,
			vitaminB12: 1.1,
			potassium: 322,
			sodium: 105,
			sugar: 12
		}
	}),
	f({
		id: 'milk-2',
		name: '2% milk',
		aliases: ['2% milk', 'reduced fat milk'],
		category: 'dairy',
		provenance: 'usda',
		servingLabel: '1 cup',
		grams: 244,
		kcal: 122,
		protein: 8,
		carbs: 12,
		fat: 5,
		micros: { calcium: 293, vitaminD: 2.9, vitaminB12: 1.3, potassium: 342, sugar: 12 }
	}),
	f({
		id: 'oatly',
		name: 'Oat milk, original',
		brand: 'Oatly',
		aliases: ['oat milk', 'oatly'],
		barcode: '190646630018',
		category: 'dairy',
		provenance: 'off',
		servingLabel: '1 cup',
		grams: 240,
		kcal: 120,
		protein: 3,
		carbs: 16,
		fat: 5,
		micros: { calcium: 350, vitaminD: 3.6, sodium: 100, fiber: 2, sugar: 7 }
	}),
	f({
		id: 'cheddar',
		name: 'Cheddar cheese',
		aliases: ['cheddar', 'cheese'],
		category: 'dairy',
		provenance: 'usda',
		servingLabel: '1 oz',
		grams: 28,
		kcal: 114,
		protein: 7,
		carbs: 0.4,
		fat: 9.4,
		micros: { calcium: 199, sodium: 174, vitaminA: 75, vitaminB12: 0.3 }
	}),
	f({
		id: 'mozzarella',
		name: 'Mozzarella, part-skim',
		aliases: ['mozzarella', 'mozz'],
		category: 'dairy',
		provenance: 'usda',
		servingLabel: '1 oz',
		grams: 28,
		kcal: 72,
		protein: 7,
		carbs: 0.8,
		fat: 4.5,
		micros: { calcium: 222, sodium: 175 }
	}),
	f({
		id: 'feta',
		name: 'Feta cheese',
		aliases: ['feta'],
		category: 'dairy',
		provenance: 'usda',
		servingLabel: '1 oz',
		grams: 28,
		kcal: 75,
		protein: 4,
		carbs: 1.2,
		fat: 6,
		micros: { calcium: 140, sodium: 316 }
	}),
	f({
		id: 'parmesan',
		name: 'Parmesan, grated',
		aliases: ['parmesan', 'parm'],
		category: 'dairy',
		provenance: 'usda',
		servingLabel: '1 tbsp',
		grams: 5,
		kcal: 21,
		protein: 1.4,
		carbs: 0.2,
		fat: 1.4,
		micros: { calcium: 55, sodium: 76 }
	}),
	f({
		id: 'butter',
		name: 'Butter',
		aliases: ['butter'],
		category: 'fat',
		provenance: 'usda',
		servingLabel: '1 tbsp',
		grams: 14,
		kcal: 102,
		protein: 0.1,
		carbs: 0,
		fat: 11.5,
		micros: { vitaminA: 97, sodium: 91 }
	}),
	f({
		id: 'olive-oil',
		name: 'Olive oil',
		aliases: ['olive oil', 'oil'],
		category: 'fat',
		provenance: 'usda',
		servingLabel: '1 tbsp',
		grams: 14,
		kcal: 119,
		protein: 0,
		carbs: 0,
		fat: 13.5,
		micros: {}
	}),
	f({
		id: 'hummus',
		name: 'Hummus',
		aliases: ['hummus'],
		category: 'fat',
		provenance: 'usda',
		servingLabel: '2 tbsp',
		grams: 30,
		kcal: 70,
		protein: 2,
		carbs: 6,
		fat: 5,
		micros: { fiber: 2, sodium: 120, iron: 0.7 }
	}),
	f({
		id: 'coffee',
		name: 'Black coffee',
		aliases: ['coffee', 'black coffee', 'americano'],
		category: 'drink',
		provenance: 'usda',
		servingLabel: '1 cup (8 oz)',
		grams: 240,
		kcal: 2,
		protein: 0.3,
		carbs: 0,
		fat: 0,
		micros: { potassium: 116, magnesium: 7 }
	}),
	f({
		id: 'espresso',
		name: 'Espresso',
		aliases: ['espresso', 'shot'],
		category: 'drink',
		provenance: 'usda',
		servingLabel: '1 shot',
		grams: 30,
		kcal: 3,
		protein: 0.1,
		carbs: 0,
		fat: 0.1,
		micros: { potassium: 34, magnesium: 24 }
	}),
	f({
		id: 'latte',
		name: 'Caffè latte, 12 oz whole milk',
		aliases: ['latte', 'cafe latte', 'starbucks latte'],
		category: 'drink',
		provenance: 'brand',
		servingLabel: '12 oz',
		grams: 355,
		kcal: 190,
		protein: 10,
		carbs: 15,
		fat: 10,
		micros: { calcium: 350, vitaminD: 3, sugar: 14, sodium: 150 }
	}),
	f({
		id: 'green-tea',
		name: 'Green tea',
		aliases: ['tea', 'green tea'],
		category: 'drink',
		provenance: 'usda',
		servingLabel: '1 cup',
		grams: 245,
		kcal: 2,
		protein: 0,
		carbs: 0.5,
		fat: 0,
		micros: {}
	}),
	f({
		id: 'orange-juice',
		name: 'Orange juice',
		aliases: ['oj', 'orange juice'],
		category: 'drink',
		provenance: 'usda',
		servingLabel: '1 cup',
		grams: 248,
		kcal: 112,
		protein: 1.7,
		carbs: 26,
		fat: 0.5,
		micros: { vitaminC: 124, potassium: 496, folate: 74, sugar: 21 }
	}),
	f({
		id: 'coke',
		name: 'Coca-Cola',
		brand: 'Coca-Cola',
		aliases: ['coke', 'cola', 'soda'],
		barcode: '049000006162',
		category: 'drink',
		provenance: 'off',
		servingLabel: '12 oz can',
		grams: 355,
		kcal: 140,
		protein: 0,
		carbs: 39,
		fat: 0,
		micros: { sodium: 45, sugar: 39 }
	}),
	f({
		id: 'sparkling-water',
		name: 'Sparkling water',
		aliases: ['la croix', 'seltzer', 'sparkling water', 'fizzy water'],
		category: 'drink',
		provenance: 'usda',
		servingLabel: '1 can',
		grams: 355,
		kcal: 0,
		protein: 0,
		carbs: 0,
		fat: 0,
		micros: {}
	}),
	f({
		id: 'red-wine',
		name: 'Red wine',
		aliases: ['wine', 'red wine'],
		category: 'drink',
		provenance: 'usda',
		servingLabel: '5 oz',
		grams: 147,
		kcal: 125,
		protein: 0.1,
		carbs: 4,
		fat: 0,
		micros: { potassium: 187, iron: 0.5 }
	}),
	f({
		id: 'beer',
		name: 'Beer, lager',
		aliases: ['beer'],
		category: 'drink',
		provenance: 'usda',
		servingLabel: '12 oz',
		grams: 356,
		kcal: 153,
		protein: 1.6,
		carbs: 13,
		fat: 0,
		micros: { potassium: 96 }
	}),
	f({
		id: 'kind-bar',
		name: 'Dark Chocolate Nuts & Sea Salt',
		brand: 'KIND',
		aliases: ['kind bar', 'kind'],
		barcode: '602652171032',
		category: 'packaged',
		provenance: 'off',
		servingLabel: '1 bar',
		grams: 40,
		kcal: 200,
		protein: 6,
		carbs: 16,
		fat: 15,
		micros: { fiber: 7, sodium: 140, potassium: 150, sugar: 5, iron: 1.4 }
	}),
	f({
		id: 'quest-bar',
		name: 'Chocolate Chip Cookie Dough',
		brand: 'Quest',
		aliases: ['quest', 'quest bar', 'protein bar'],
		barcode: '888849000445',
		category: 'packaged',
		provenance: 'off',
		servingLabel: '1 bar',
		grams: 60,
		kcal: 200,
		protein: 21,
		carbs: 21,
		fat: 8,
		micros: { fiber: 14, sodium: 220, calcium: 130, sugar: 1 }
	}),
	f({
		id: 'cheerios',
		name: 'Cheerios',
		brand: 'General Mills',
		aliases: ['cheerios', 'cereal'],
		barcode: '016000275273',
		category: 'packaged',
		provenance: 'off',
		servingLabel: '1.5 cups (39 g)',
		grams: 39,
		kcal: 140,
		protein: 5,
		carbs: 29,
		fat: 2.5,
		micros: { fiber: 4, iron: 5.4, sodium: 190, folate: 200 }
	}),
	f({
		id: 'dark-chocolate',
		name: 'Dark chocolate, 70%',
		aliases: ['chocolate', 'dark chocolate'],
		category: 'packaged',
		provenance: 'usda',
		servingLabel: '1 oz',
		grams: 28,
		kcal: 170,
		protein: 2.2,
		carbs: 13,
		fat: 12,
		micros: { iron: 3.3, magnesium: 64, fiber: 3, sugar: 7 }
	}),
	f({
		id: 'honey',
		name: 'Honey',
		aliases: ['honey'],
		category: 'condiment',
		provenance: 'usda',
		servingLabel: '1 tbsp',
		grams: 21,
		kcal: 64,
		protein: 0.1,
		carbs: 17,
		fat: 0,
		micros: { sugar: 17 }
	}),
	f({
		id: 'maple',
		name: 'Maple syrup',
		aliases: ['maple', 'syrup'],
		category: 'condiment',
		provenance: 'usda',
		servingLabel: '1 tbsp',
		grams: 20,
		kcal: 52,
		protein: 0,
		carbs: 13,
		fat: 0,
		micros: { sugar: 12 }
	}),
	f({
		id: 'ketchup',
		name: 'Ketchup',
		aliases: ['ketchup'],
		category: 'condiment',
		provenance: 'usda',
		servingLabel: '1 tbsp',
		grams: 17,
		kcal: 19,
		protein: 0.2,
		carbs: 4.5,
		fat: 0,
		micros: { sodium: 160, sugar: 3.7 }
	}),
	f({
		id: 'mayo',
		name: 'Mayonnaise',
		aliases: ['mayo', 'mayonnaise'],
		category: 'condiment',
		provenance: 'usda',
		servingLabel: '1 tbsp',
		grams: 14,
		kcal: 94,
		protein: 0.1,
		carbs: 0.1,
		fat: 10,
		micros: { sodium: 88 }
	}),
	f({
		id: 'salsa',
		name: 'Salsa',
		aliases: ['salsa'],
		category: 'condiment',
		provenance: 'usda',
		servingLabel: '2 tbsp',
		grams: 32,
		kcal: 10,
		protein: 0.5,
		carbs: 2,
		fat: 0.1,
		micros: { sodium: 150, vitaminC: 4 }
	}),
	f({
		id: 'popcorn',
		name: 'Popcorn, air-popped',
		aliases: ['popcorn'],
		category: 'packaged',
		provenance: 'usda',
		servingLabel: '3 cups',
		grams: 24,
		kcal: 93,
		protein: 3,
		carbs: 19,
		fat: 1.1,
		micros: { fiber: 3.6, magnesium: 36 }
	}),
	f({
		id: 'rice-cake',
		name: 'Brown rice cake',
		aliases: ['rice cake'],
		category: 'packaged',
		provenance: 'usda',
		servingLabel: '1 cake',
		grams: 9,
		kcal: 35,
		protein: 0.7,
		carbs: 7.3,
		fat: 0.3,
		micros: { sodium: 29 }
	}),
	f({
		id: 'pizza-slice',
		name: 'Cheese pizza, 1 slice',
		aliases: ['pizza', 'pizza slice'],
		category: 'prepared',
		provenance: 'community',
		servingLabel: '1 slice (1/8 of 14")',
		grams: 107,
		kcal: 285,
		protein: 12,
		carbs: 36,
		fat: 10,
		micros: { sodium: 640, calcium: 180, fiber: 2.5 }
	}),
	f({
		id: 'egg-mcmuffin',
		name: 'Egg McMuffin',
		brand: "McDonald's",
		aliases: ['mcmuffin', 'egg mcmuffin'],
		category: 'prepared',
		provenance: 'brand',
		servingLabel: '1 sandwich',
		grams: 132,
		kcal: 310,
		protein: 17,
		carbs: 30,
		fat: 13,
		micros: { sodium: 770, calcium: 230, iron: 2.7, fiber: 2 }
	}),
	f({
		id: 'big-mac',
		name: 'Big Mac',
		brand: "McDonald's",
		aliases: ['big mac'],
		category: 'prepared',
		provenance: 'brand',
		servingLabel: '1 sandwich',
		grams: 215,
		kcal: 590,
		protein: 25,
		carbs: 46,
		fat: 34,
		micros: { sodium: 1050, fiber: 3, calcium: 140, iron: 4.5 }
	}),
	f({
		id: 'chipotle-bowl',
		name: 'Chicken burrito bowl',
		brand: 'Chipotle',
		aliases: ['chipotle', 'burrito bowl', 'chipotle bowl'],
		category: 'prepared',
		provenance: 'brand',
		servingLabel: '1 bowl (chicken, rice, beans, salsa, lettuce)',
		grams: 540,
		kcal: 630,
		protein: 47,
		carbs: 71,
		fat: 16,
		micros: { fiber: 14, sodium: 1540, potassium: 980, iron: 4.2 }
	}),
	f({
		id: 'california-roll',
		name: 'California roll',
		aliases: ['sushi', 'california roll'],
		category: 'prepared',
		provenance: 'community',
		servingLabel: '6 pieces',
		grams: 175,
		kcal: 255,
		protein: 7,
		carbs: 38,
		fat: 7,
		micros: { sodium: 520, fiber: 2 }
	}),
	f({
		id: 'dates',
		name: 'Medjool dates',
		aliases: ['date', 'dates'],
		category: 'produce',
		provenance: 'usda',
		servingLabel: '2 dates',
		grams: 48,
		kcal: 133,
		protein: 0.9,
		carbs: 36,
		fat: 0.1,
		micros: { fiber: 3.2, potassium: 334, magnesium: 26, sugar: 32 }
	})
];

export const CATEGORY_LABEL: Record<string, string> = {
	protein: 'Protein',
	dairy: 'Dairy',
	grain: 'Grains',
	produce: 'Produce',
	fat: 'Fats & nuts',
	drink: 'Drinks',
	packaged: 'Packaged',
	condiment: 'Condiments',
	prepared: 'Prepared'
};

export const PROVENANCE_LABEL: Record<Provenance, { title: string; detail: string }> = {
	usda: { title: 'USDA', detail: 'Lab-analyzed · public domain' },
	off: { title: 'Open Food Facts', detail: 'Community · ODbL' },
	lab: { title: 'Lab-analyzed', detail: 'Third-party assay' },
	brand: { title: 'Brand published', detail: 'Manufacturer nutrition' },
	community: { title: 'Community', detail: 'Estimated from similar foods' }
};
